### ISSUE TITLE
Working alternatives in 2023

### ISSUE THREAD

**Issue by hartwork** [meithecatte/fake-static#4]
Hi!

For those looking for options working in 2023 for the few(?) cases where extending the lifetime of a reference to `'static` is indeed needed, these resources could be of interest:

- https://github.com/That3Percent/extend-lifetime/blob/master/src/lib.rs
- https://doc.rust-lang.org/std/mem/fn.transmute.html#examples
- https://crates.io/crates/bounded-static

If there is interest to add these links to the readme, I can make a pull request. Keeping this ticket open would also be an option.

Best, Sebastian

**Comment by meithecatte** [comment]
Updated the README. Please be safe. Don't drink and drive, don't mix stimulants with depressants, don't use code straight out of an I-unsound issue to achieve your goals, and always wear a seatbelt.

**Comment by hartwork** [comment]
@meithecatte I'm assuming you refer to commit 964c05b0c1396bf57e112524774f8cbdd4ae46f5 but I don't see any of the links in there. I guess that's intentional then, okay.

**Comment by hartwork** [comment]
@meithecatte PS: With the segfault in mind, I wonder if #2 and #3 are from a different past or just humor then?

**Comment by meithecatte** [comment]
> @meithecatte I'm assuming you refer to commit [964c05b](https://github.com/meithecatte/fake-static/commit/964c05b0c1396bf57e112524774f8cbdd4ae46f5) but I don't see any of the links in there. I guess that's intentional then, okay.

Yeah, I feel like the area of unsafe code is tricky enough that it would be more responsible to point any potential user to the documentation on the full weight of this dark corner of the language, rather than simply providing answers that will let them shoot themselves in the foot.

For example, `extend-lifetime` doesn't even have any documentation on what assumptions you need to uphold.

> @meithecatte PS: With the segfault in mind, I wonder if #2 and #3 are from a different past or just humor then?

Being familiar with all the context, it definitely feels like circlejerk.

**Comment by hartwork** [comment]
> For example, `extend-lifetime` doesn't even have any documentation on what assumptions you need to uphold.

Personally I expect that its users need to make sure that the lifetime-extended object is practically not used beyond it's de-facto lifetime, that the staticity is a lie that only fools the compiler. The function signature signals the `unsafe` nature if this tool so I would hope that everyone playing with the idea of using it has some bells ringing asking if there are other ways. Is there more to it? I'd be happy to know.

**Comment by meithecatte** [comment]
Well, why would you ever need to fool the compiler like that? Also, lifetimes are used to prove many guarantees other than "the memory hasn't been freed yet".

**Comment by hartwork** [comment]
> Well, why would you ever need to fool the compiler like that?

@meithecatte my case is with the "log" crate that is asking for the logger to have static lifetime (`set_logger`) and I wanted to send its output to an `anstream::RawStream` so that it can be (a) real stdout/stderr by default but also (b) a buffer (`anstream::Buffer`) to allow capturing and comparing to expected output in the test suite. The test suite is creating buffer instances as non-static on the fly but the logger needs to *think* these are static. I'm currently considering to say goodbye to static loggers and the log crate altogether. It seems like I have to chose between these two: fake static or ditch the log crate. What do you think?

> Also, lifetimes are used to prove many guarantees other than "the memory hasn't been freed yet".

If you have time to elaborate and/or share some links, I'd be curious what you have in mind.

**Comment by meithecatte** [comment]
> The test suite is creating buffer instances as non-static on the fly but the logger needs to _think_ these are static

Are you doing that per testcase? `log::set_logger` can only be called once in the lifetime of the process, further calls will just error out and do nothing.

Other than that, since you're not dealing with `Buffer<'a>`, but only `&'a Buffer`, you could explore using `Arc<Buffer>` or `Box::leak`.

> If you have time to elaborate and/or share some links, I'd be curious what you have in mind.

Well, a `&'a T` asserts that outside of an `UnsafeCell`, nothing will mutate the `T` it is pointing to. SImilarly, a `&'a mut T` asserts that all accesses to the `T` it is pointing to will go through this reference as long as it is live. Apart from general type system guarantees that follow from this (iterator invalidation and thread safety are the big ones), there are APIs like [`Mutex::get_mut`](https://doc.rust-lang.org/stable/std/sync/struct.Mutex.html#method.get_mut) that take advantage of this. And then you can use the lifetimes for more advanced typesystem magic, such as [`GhostCell`](https://lib.rs/crates/ghost-cell).

I suggest you ask your question on a forum like users.rust-lang.org, or one of the Rust discord serveres.

**Comment by hartwork** [comment]
@meithecatte thanks for your reply!

> > The test suite is creating buffer instances as non-static on the fly but the logger needs to _think_ these are static
> 
> Are you doing that per testcase? `log::set_logger` can only be called once in the lifetime of the process, further calls will just error out and do nothing.

That is clear, the logger is the same to the eyes of the log crate every time; in the test suite it is already set to the right thing the second time around. (The only-succeed-once nature of  `log::set_logger` is rather unfortunate design, it could hardly be more hostile to composition and automated testing.)

> Other than that, since you're not dealing with `Buffer<'a>`, but only `&'a Buffer`, you could explore using `Arc<Buffer>` or `Box::leak`.

I understand the idea about `Arc<Buffer>` but I would need to say goodbye to the `anstream::RawStream` abstraction/unification then and distinct between stdout, stderr and the buffer in code more. So that would be the third option: saying goodbye to `anstream::RawStream` and moving the buffer into the logger. (What I have at the moment is `Arc<Mutex<&'static mut dyn RawStream>>`.)

> I suggest you ask your question on a forum like users.rust-lang.org, or one of the Rust discord servers.

I understand that we are not at a Rust support forum here. Thanks for your time!

PS: The related code is Software Libre and by no means secret, it's in https://github.com/hartwork/rust-for-it if you're curious.
